[pytest]
filterwarnings =
    ignore:Module already imported so cannot be rewritten; _hypothesis_globals
    ignore:Module already imported so cannot be rewritten; hypothesis
    ignore:Module already imported so cannot be rewritten; schemathesis
